version: "3.7"
networks:
  backend:
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    depends_on:
      - web
  web:
    build: .
    ports:
      - 8080:8080
    links:
      - redis
      - postgres
    networks:
      - backend
    env_file: docker.env
  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file: docker.env
    volumes:
      - "pg-data:/var/lib/postgresql/data"  
volumes:
  pg-data:      
